data_directory: sample_input_files
fail_on_hash_mismatch: false

read:
 - where:
     data_product: human/compartment-transition
   use:
     version: 1.0.0
 - where:
     data_product: human/population
   use:
     version: 1.0.0
 - where:
     data_product: human/commutes
   use:
     version: 1.0.0
 - where:
     data_product: human/mixing-matrix
   use:
     version: 2.0.0
 - where:
     data_product: human/infectious-compartments
   use:
     version: 1.0.0
 - where:
     data_product: human/infection-probability
   use:
     version: 2.0.0
 - where:
     data_product: human/movement-multipliers
   use:
     version: 2.0.0
 - where:
     data_product: human/initial-infections
   use:
     version: 2.0.0
 - where:
     data_product: human/trials
   use:
     version: 1.0.0
 - where:
     data_product: human/start-end-date
   use:
     version: 2.0.0
 - where:
     data_product: human/stochastic-mode
   use:
     version: 1.0.0
 - where:
     data_product: human/random-state
   use:
     version: 1.0.0
 - where:
     data_product: human/abcsmc-parameters
   use:
     version: 1.0.0
 - where:
     data_product: human/historical-deaths
   use:
     version: 2.0.0
