name: simple_network_sim
channels:
  - defaults
  - scottishcovidresponse
dependencies:
  # install dependencies
  - python=3.7
  - networkx=2.4
  - matplotlib=3.1.3
  - pandas=1.0.3
  - data_pipeline_api=0.0.1

  # test dependencies
  - coverage=5.0
  - pytest=5.4.1
  - pytest-cov=2.8.1
